title: Data Structures and Algorithms
repo: https://github.com/joshsj/dsa

references:
  - id: lastAlgo
    title: The Last Algorithms Course You'll Need
    by: ThePrimeagen
    url: https://frontendmasters.com/courses/algorithms

  - id: commonSense
    title: A Common-Sense Guide to Data Structures and Algorithms
    by: Jay Wengrow
    url: https://www.oreilly.com/library/view/a-common-sense-guide/9781680502794/

pages:
  - id: time-complexity
    title: Time Complexity
    srcPath: time-complexity.md

