title: Data Structures & Algorithms
repo: https://github.com/joshsj/dsa

pages:
  - id: array-lists
    title: Array Lists
    srcPath: array-lists.md
    impl: array-list.zig
    hidden: true

  - id: binary-trees
    title: Binary Trees
    srcPath: binary-trees.md

  - id: bst
    title: Binary Search Trees
    srcPath: binary-search-trees.md

  - id: graphs
    title: Graphs
    srcPath: graphs.md

  - id: hash-functions
    title: Hash Functions
    srcPath: hash-functions.md

  - id: hash-maps-sets
    title: Hash Maps/Sets
    srcPath: hash-maps-sets.md

  - id: heaps
    title: Heaps
    srcPath: heaps.md
    impl: heap.zig

  - id: recursion
    title: Recursion
    srcPath: recursion.md

  - id: time-complexity
    title: Time Complexity
    srcPath: time-complexity.md

references:
  - id: last-algo
    title: The Last Algorithms Course You'll Need
    by: ThePrimeagen
    url: https://frontendmasters.com/courses/algorithms

  - id: common-sense
    title: A Common-Sense Guide to Data Structures and Algorithms
    by: Jay Wengrow
    url: https://www.oreilly.com/library/view/a-common-sense-guide/9781680502794/

  - id: ds-ucsd
    title: Data Structures at USDC
    by: Niema Moshiri
    url: https://cogniterra.org/course/330

  - id: hash-table-wiki
    title: Hash table
    by: Wikipedia
    url: https://en.wikipedia.org/wiki/Hash_table

  - id: recursion-wiki
    title: Recursion
    by: Wikipedia
    url: https://en.wikipedia.org/wiki/Recursion

terms:
  - id: hash-coll
    title: Hash collision
    definition: >-
      A value that is produced by the hash function for different inputs.

  - id: hash-func
    title: Hash function
    definition: >-
      A deterministic, consistent function that maps data of an arbitrary length
      to a fixed length.

  - id: load-factor
    title: Load factor
    definition: >-
      The ratio of elements to capacity in a data structure.

  - id: linear-ds
    title: Linear data structure
    definition: >-
      A data structure that stores a sequence of values.

      E.g., array lists, linked lists, stacks, and queues.
    see:
      - non-linear-ds

  - id: non-linear-ds
    title: Non-Linear data structure
    definition: >-
      A data structure that stores a hierarchy of values.

      E.g., trees and graphs.
    see:
      - linear-ds

  - id: recursion
    title: Recursion
    definition: >-
      A process which depends on a simpler or previous version of itself.


