name: Deploy Notes
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BRANCH: notes-deploy
      REPO: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

    steps:
      - name: echo variables
        run: |
          echo "repository url: $REPO"
          echo "deployment branch: $BRANCH"

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: clone repository
        run: git clone $REPO .

      - name: delete .git folder
        run: rm -rf ./.git/

      - name: build
        working-directory: notes-build
        run: |
          npm ci
          npm run build

      - name: init repository
        working-directory: notes-build/build
        run: |
          git init
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add origin $REPO

      - name: push
        working-directory: notes-build/build
        run: |
          git checkout -b $BRANCH
          git add .
          git commit -m Deploy
          git push --force origin $BRANCH

